title: Embedded Linux and beyond
description: >- # this means to ignore newlines until "baseurl:"
  Blog about open-source software, Internet of Things (IoT), embedded Linux
  development and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mirzak
linkedin_username: mirzakrak
author: Mirza Krak

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo
